---
- name: Install exa
  become: yes
  ansible.builtin.dnf:
    name: exa
    state: latest

- name: Install bat
  become: yes
  ansible.builtin.dnf:
    name: bat
    state: latest

- name: Install ranger
  become: yes
  ansible.builtin.dnf:
    name: ranger
    state: latest
