---
- name: Backup existing bash files
  ignore_errors: yes
  ansible.builtin.command:
    cmd: mv ~/.bashrc ~/.bashrc.bk; mv ~/.bash_profile ~/.bash_profile.bk

- import_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Stow bash
  ansible.builtin.command:
    chdir: "{{ playbook_dir }}"
    cmd: stow bash
