---
- name: Backup existing bash files
  ignore_errors: yes
  ansible.builtin.shell:
    cmd: mv {{ item }} {{ item }}.bk
    creates: "{{ item }}.bk"
  loop:
    - "$HOME/.bashrc"
    - "$HOME/.bash_profile"

- import_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Stow bash
  ansible.builtin.command:
    chdir: "{{ playbook_dir }}"
    cmd: stow bash
