---
- name: Install required packages for Docker on Fedora
  become: yes
  ansible.builtin.dnf:
    update_cache: yes
    name:
      - dnf-plugins-core
    state: latest

- name: Add Docker repository
  become: yes
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Install Docker
  become: yes
  ansible.builtin.dnf:
    update_cache: yes
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  ignore_errors: "{{ ansible_check_mode }}"
