k9s:
  screenDumpDir: /home/tyag/.local/state/k9s/screen-dumps
  readOnly: true
  defaultView: ""
  noExitOnCtrlC: false
  ui:
    skin: catppuccin-mocha-transparent
    enableMouse: true
    headless: false
    logoless: true
    crumbsless: false
    reactive: false  # Toggles reactive UI. This option provide for watching on disk artifacts changes and update the UI live  Defaults to false.
    noIcons: true
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreen: false
    textWrap: true
    showTime: true
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
