---
- import_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Install and update pip
  ansible.builtin.command:
    cmd: python -m ensurepip --upgrade && python -m pip install --upgrade pip

- name: Ensure ditfiles are up to date
  ignore_errors: "{{ check_mode }}"
  ansible.builtin.git:
    repo: "https://github.com/tyagdit/ditfiles"
    dest: "{{ playbook_dir }}"
