---
- import_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Create autoload dir
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share/nvim/site/autoload"
    state: directory

- name: Install vim-plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_user_dir }}/.local/share/nvim/site/autoload/plug.vim"

- name: Install nvim plugins
  ansible.builtin.command:
    cmd: nvim +PlugInstall +qall
